# Problem 1

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matrix= np.random.uniform(0.10,size=(5,))

# 3 - matris'in boyutunu öğrenin
matrix_shape= matrix.shape

# 4 - matris'i yeniden boyutlandırın
resized_matrix= matrix.reshape((1,5))

# 5 - matris'in boyut sayısını öğrenin
dimension_count= resized_matrix.ndim 

# Problem 2

In [7]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

import numpy as np

odd_matrix = np.arange(1, 12, 2).reshape(2, 3)

print(odd_matrix)
# 2 - Oluşturduğunuz matrisi parçalayın
sub_matrices = np.split(odd_matrix, 2)

# 3 - Parçalanmış matrisleri birleştirin
concatenated_matrix = np.concatenate(sub_matrices) 


[[ 1  3  5]
 [ 7  9 11]]


# Problem 3

In [8]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
import numpy as np

matrix = np.random.choice(np.arange(5, 101, 2), size=(5, 2))
print(matrix)

# 2 - matris'in özelliklerini inceleyin

print("Boyut:", matrix.shape)
print("Boyut sayısı:", matrix.ndim)
print("Eleman sayısı:", matrix.size)
print("Veri tipi:", matrix.dtype)
print("En küçük eleman:", np.min(matrix))
print("En büyük eleman:", np.max(matrix))
print("Toplam:", np.sum(matrix))
print("Ortalama:", np.mean(matrix))
print("Standart sapma:", np.std(matrix))

[[57 37]
 [43 77]
 [37 85]
 [79 31]
 [53 55]]
Boyut: (5, 2)
Boyut sayısı: 2
Eleman sayısı: 10
Veri tipi: int32
En küçük eleman: 31
En büyük eleman: 85
Toplam: 554
Ortalama: 55.4
Standart sapma: 18.260339536821323
